#InterfaceError.py

class InterfaceError(Exception):
    """exception generated by an interface, usually due to a communications
    failure."""
    def __init__(self, value):
        self.value = value
    def __str__(self):
        return repr(self.value)
